# Generated by Django 5.2.3 on 2025-06-15 02:54

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0002_classe_etudiants_alter_classe_enseignant_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='quizsession',
            name='etudiant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sessions', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='quizsession',
            name='score',
            field=models.FloatField(default=0),
        ),
        migrations.AddConstraint(
            model_name='quizsession',
            constraint=models.UniqueConstraint(fields=('quiz', 'etudiant'), name='unique_quiz_attempt_per_student'),
        ),
    ]
